name: "palgen"

inputs:
  conan:
    description: Install the optional conan dependency
    required: false
    default: 'false'

  run:
    description: Run palgen
    required: false
    default: 'true'
  
  requirements:
    description: Path to extension requirements.txt
    required: false
    default: ''

runs:
  using: "composite"
  steps:    
  - name: Setup Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.11'
  
  - name: Install Conan
    shell: bash
    if: inputs.conan == 'true'
    run: pip install conan --upgrade

  - name: Install palgen
    shell: bash
    run: |
      pip install git+https://github.com/palliate/palgen.git@master

  - name: Install extension dependencies
    shell: bash
    if: inputs.requirements != ''
    run: pip install -r ${{ inputs.requirements }}

  - name: Run palgen
    shell: bash
    if: inputs.run == 'true'
    run: palgen