name: "Enable palgen"

inputs:
  key:
    description: Repository key - TODO delete once repository is public
    required: true
  conan:
    description: Install the optional conan dependency
    required: false

runs:
  using: "composite"
  steps:    
  - name: Setup Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.10'
  
  - uses: webfactory/ssh-agent@v0.7.0
    with:
      ssh-private-key: ${{ inputs.key }}

  - name: Install Conan
    if: inputs.conan == true
    shell: bash
    run: |
      pip install conan --upgrade
      conan --version

  - name: Install palgen
    shell: bash
    run: |
      pip install git+ssh://git@github.com/palliate/palgen.git