name: "Install palgen"

inputs:
  conan:
    description: Install the optional conan dependency
    required: false

  run:
    description: Run palgen
    required: false
    default: true

runs:
  using: "composite"
  steps:    
  - name: Setup Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.11'
  
  - name: Install Conan
    shell: bash
    if: inputs.conan == true
    run: pip install conan --upgrade

  - name: Install palgen
    shell: bash
    run: |
      pip install git+https://github.com/palliate/palgen.git@master
  
  - name: Run palgen
    shell: bash
    if: inputs.run == true
    run: palgen