name: "Run palgen"

inputs:
  conan:
    description: Install the optional conan dependency
    required: false

runs:
  using: "composite"
  steps:    
  - name: Setup Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.10'
  
  - name: Install Conan
    shell: bash
    run: |
      [[ "${{ inputs.conan }}" = true ]] && pip install conan --upgrade

  - name: Install palgen
    shell: bash
    run: |
      pip install git+ssh://git@github.com/palliate/palgen.git