name: "Enable palgen"

inputs:
  key:
    description: Repository key - TODO delete once repository is public
    required: true

runs:
  using: "composite"
  steps:    
  - name: Setup Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.10'
  
  - uses: webfactory/ssh-agent@v0.7.0
    with:
      ssh-private-key: ${{ inputs.key }}

  - name: Install palgen
    working-directory: build/palgen
    shell: bash
    run: |
      pip install git+ssh://git@github.com/palliate/palgen.git