[project]
name = "cmake_example"
version = "1.0.0"
folders = ["src"]

#[preprocess]
#enabled = false
#foo = "bar"
#bar = 5
#foobar = true
[test]
name = "cmake_example"
version = "1.0.0"
folders = ["src"]